### ISSUE TITLE
Potential problem with manifest.yml

### ISSUE THREAD

**Issue by phiwoff** [indaco/predix-ec-configurator#1]
My Gateway agent would not successfully run with the provided/generated manifest.yml, however when I used [this variation](https://github.com/phiwoff/predix-ec-configurator/blob/master/ec-templates/gateway-manifest.tpl.yml), the Gateway pushed and ran.

While there is some utility in having a _--no-start command_ on the EC Server agent, I do not recommend it for the EC Gateway. It is actually very helpful to ensure the Gateway will start up before moving onto the Diego and route mapping portions of the push process. With that said, I am going to add the _no-route_ option to our team's recommended manifest.yml config and update our instructions accordingly.

**Comment by indaco** [comment]
Thanks for bringing this up, fixed with latest commit. This closes #1
